### ISSUE TITLE
document `CLArrays.init`

### ISSUE THREAD

**Issue by ssfrr** [JuliaGPU/CLArrays.jl#13]
The README shows calling the `init` function before creating a GPU array, but it seems to work to just create the array without `init`. Is `init` required? What does it actually do?

**Comment by SimonDanisch** [comment]
If you don't init explicitly, it will init with some defaults.
This is the code to select a default device:
https://github.com/JuliaGPU/CLArrays.jl/blob/master/src/context.jl#L24

It prioritizes GPU backends and just selects the first one in the list!
