### ISSUE TITLE
Custom types seem pretty broken (particularly dual numbers)

### ISSUE THREAD

**Issue by MikeInnes** [JuliaGPU/CLArrays.jl#17]
Basic stuff works, but anything more complex breaks down:
```julia
julia> xs = CLArray(Dual.([-1, 0, 1],1))

julia> xs .* 2
GPU: 3-element Array{ForwardDiff.Dual{Void,Int64,1},1}:
 Dual{Void}(-2,2)
  Dual{Void}(0,2)
  Dual{Void}(2,2)

julia> exp.(xs) # generates a huge trace
ERROR: CLError(code=-11, CL_BUILD_PROGRAM_FAILURE)

julia> relu.(xs)
ERROR: Method select_value(Bool, ForwardDiff.Dual{Void,Int64,1}, ForwardDiff.Dual{Void,Int64,1}) doesn't exist!
```

**Comment by SimonDanisch** [comment]
The first one seems like I overload the `exp` intrinsic for all numbers, but they only exist for Int.
The second one I thought I already fixed... I have a look!

**Comment by MikeInnes** [comment]
cc @Maaarcocr, who was playing around with this as well.

**Comment by SimonDanisch** [comment]
fixed in https://github.com/SimonDanisch/Transpiler.jl/releases/tag/v0.4.6

**Comment by Maaarcocr** [comment]
@SimonDanisch should the CLArrays.jl REQUIRE be changed to use the changes made to Transpiler.jl?

**Comment by SimonDanisch** [comment]
Ah yes, that'd make sense!

**Comment by MikeInnes** [comment]
Awesome!
