### ISSUE TITLE
threads number

### ISSUE THREAD

**Issue by rveltz** [JuliaGPU/CLArrays.jl#25]
Hi,

I want to check the specs of my GPU on a McBook pro. I get 

```julia
CLArrays.init(CLArrays.devices()[2])
OpenCL context with:
CL version: OpenCL 1.2
Device: CL AMD Radeon Pro 560 Compute Engine
            threads: 256
             blocks: (256, 256, 256)
      global_memory: 4294.967296 mb
 free_global_memory: NaN mb
       local_memory: 0.032768 mb
```

However, from [here](https://www.amd.com/fr/graphics/workstations-radeon-pro-500), I would expect 1024 threads. Am I missing something?

Thank you

Bests

**Comment by SimonDanisch** [comment]
These are not the number of stream processors - and the name is probably missleading.
It's the `max_work_group_size`, which is the same as in cuda `MAX_THREADS_PER_BLOCK` and is more about the number that you can use when launching a kernel on the gpu:
```Julia
if threads <= threads(device) 
gpu_call(func, (arg1, arg2, ...), (blocks, threads))
end
