### ISSUE TITLE
How to select which OpenCL device 

### ISSUE THREAD

**Issue by frenchfaso** [JuliaGPU/CLArrays.jl#9]
Is it possible to select one particular GPU if there are many available?
Or does CLArrays use automatically all GPUs?
Thanks!

**Comment by SimonDanisch** [comment]
This is documented in the readme:


>The only noteworthy functionality that isn't part of the GPUArray interface is how to select and initialize devices:
```Julia
using CLArrays

for dev in CLArrays.devices()
    CLArrays.init(dev)
    x = zeros(CLArray{Float32}, 5, 5) # create a CLArray on device `dev`
end
# you can also filter with is_gpu, is_cpu
gpu_devices = CLArrays.devices(is_gpu)
```

**Comment by frenchfaso** [comment]
Thanks, sorry, I jumped straight to the GPUArray readme :-P
So if I want to distribute some calculations on several GPUs I would do something like:
```julia
using CLArrays

gpu1 = CLArrays.devices(is_gpu)[1]
CLArrays.init(gpu1)
# do some work on GPU1

gpu2 = CLArrays.devices(is_gpu)[2]
CLArrays.init(gpu2)
# do other stuff on GPU2
# etc..
```

**Comment by SimonDanisch** [comment]
Yeah that should work!
